name: Code Deploy

on:
  workflow_dispatch:
    inputs:
      key_test:
        description: input key
        type: string
        required: true

jobs:
  codedeploy:
    runs-on: ubuntu-latest
    environment: 'dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

