name: CodeDeploy staging

on:
  workflow_dispatch:
    inputs:
      application_name:
        type: choice
        required: true
        options:
          - api
          - client
      application_repository_ref:
        description: application repository ref (branch or tag or commit-hash)
        type: string
        required: true

jobs:
  codedeploy:
    runs-on: ubuntu-latest
    environment: 'dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

